### ISSUE TITLE
Add Release Drafter for the repository

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/meshery-adapter-template#13]
**Enhancement Description**
Each of the layer5 repositories needs releaseDrafter automation as had been done in the meshery project which takes care of drafting release notes.

**Related Challenges**
Add ReleaseDrafter configuration yaml file & GitHub Action.

---

 **Additional context**
[Rlease Drafter configuration file](https://github.com/layer5io/meshery/blob/master/.github/release-drafter.yml)
[Release Drafter GitHub action](https://github.com/layer5io/meshery/blob/master/.github/workflows/release-drafter.yml)

**Comment by leecalcote** [comment]
Thank you, @Anita-ihuman. This would be great.

**Comment by leecalcote** [comment]
@Anita-ihuman will you have another look at this item?

**Comment by FujishigeTemma** [comment]
I'll try this issue, for my first issue on layer5 🙌
